### PR TITLE
Updating podspec

### PR DESCRIPTION
**Pull request by mbarnach**
Update the podspec to use the latest version.
Once merge, Cocoapod will be updated.

### CODE REVIEW

**Review by futurejones — APPROVED** [review]
Looks good.

**Comment by dannys42** [comment]
@mbarnach Just wanted to confirm this now requires a minimum swift version of 5.1?  (i.e. it does not work on Swift 5.0.1 anymore?  The package.swift file still refers to Swift tools 5.0)

**Comment by mbarnach** [comment]
The reason is actually the `.swift-version` we are shipping. It is set to 5.1, so `pod spec lint LoggerAPI.podspec` returns an error. I guess it was "admitted" that we need 5.1.
I can revert it back, but then we also need to change the `.swift-version` file.
IMO, it would be better to keep moving forward to not have too many version to handle, and changing the `.swift-version` file can break some other compatibility.

**Comment by dannys42** [comment]
I see.  In this case, since the .swift-version was already there, I think you did the right thing.  But in general, I don't think we should do a version bump without some sort of announcement or timeline or something.  We risk breaking things for people if we are too aggressive in raising our minimum version requirements.

**Review by dannys42 — APPROVED** [review]

**Comment by mbarnach** [comment]
@dannys42 Fully agree with you. But I think the state of the support for the Swift versions is quite unclear unfortunately. It seems like 5.1 is the default base, but we (partly) support other versions (depending on how you request Kitura). Clarification will have to be done at some point.

Regardless, I will now publish the Cocoapod, thanks for merging it.

**Comment by dannys42** [comment]
@mbarnach My strategy right now is just to ensure everything that was working continues to work after the org change.  Anything that requires more than minor changes should be identified and then we can decide what to do afterwards.  The CI tests are generally consistent in the versions of swift they test, but not universally so.  I agree we'll probably want to drop support for older versions of Swift, but there will always be multiple versions and platforms we'll have to worry about.  And once we have 2 versions, I don't see much more overhead in supporting "n" versions as long as we have good automation.

**Pull request merged**
